# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170330_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='/meida/default.png', upload_to='treasure_images'),
        ),
    ]
